// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SneaksUpWrongPasswordTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sneaksUpWrongPassword() {
    driver.get("https://www.sneaksup.com/");
    driver.manage().window().setSize(new Dimension(1344, 816));
    driver.findElement(By.cssSelector(".customer-link > .header-icons")).click();
    driver.findElement(By.id("mail_t2")).click();
    driver.findElement(By.id("mail_t2")).sendKeys("selimyaylali1@gmail.com");
    driver.findElement(By.id("Password")).click();
    driver.findElement(By.id("Password")).sendKeys("dsjadhjsadhjash");
    driver.findElement(By.id("submit_t2")).click();
    assertThat(driver.findElement(By.xpath("//span[contains(.,\'Giriş başarısız oldu.\')]")).getText(), is("Giriş başarısız oldu."));
    driver.findElement(By.xpath("//span[contains(.,\'Giriş başarısız oldu.\')]")).click();
  }
}
